config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # resources :users, only: %i[show] do
  #   resources :reading_groups, only: %i[show] do
  #     resources :questions, only: %i[new create show] do
  #       resources :answers, only: %i[show new create]
  #     end
  #   end
  # end
  resources :users

  resources :reading_groups

  resources :daily_readings

  resources :answers

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :messages, only: :create


end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

# 10.times do
#   User.create!(
#     email: Faker::Internet.email,
#     password: '123456'
#   )
# end

# 10.times do
#   ReadingGroup.create!(
#     user: User.all.sample
#   )
# end

app/views/shared/_answer_row.html.erb
<div class="answer-row">
  <p class="font-weight-bold"><%= current_user.name %>:</p>
  <p><%= answer %></p>
</div>

app/views/shared/_chatroom.html.erb
<% if chatroom %>
  <h1><%= chatroom.name %></h1>
  <div id="messages" data-chatroom-id="<%= chatroom.id %>">
    <% chatroom.messages.each do |message| %>
      <div class="message-container" id="message-<%= message.id %>">
        <i class="author">
          <span><%= message.user.name %></span>
          <small><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></small>
        </i>
        <p><%= message.content %></p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
    <p class="fancy-link m-2"><%= link_to "About", "#" %></p>
    <p class="fancy-link m-2"><%= link_to "Privacy", "#" %></p>
    <p class="fancy-link m-2"><%= link_to "Disclosure & Disclaimer", "#" %></p>
  </div>
  <div class="footer-copyright">
    Copyright @ <%= Date.today.year %> Buzz Reads
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="display: table;">
  <%= link_to :root, class: "navbar-brand" do %>

    <div id="logo" class="p-2" style="display: table-cell;">
      <%# <%= cl_image_tag("buzz_reads_r1zkbs") %>
      <%= cl_image_tag("https://res.cloudinary.com/dm37aktki/image/upload/v1647009589/ms-icon-310x310_zsl4lv.png") %>
    </div>
    <div class="head-title px-5" style="display: table-cell;">
      <h1 class="pt-2" id="nav-title">Buzz Reads</h1>
    </div>
    <%# <div class="head-tagline" style="display: table-cell;">
      <p>Guided Reading Made Easy</p>
    </div> %>

  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent" style="display: table-cell;">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <% if current_user.teacher %>
          <li class="nav-item active fancy-link m-3">
            <%= link_to "Your Reading Groups", reading_groups_path%>
          </li>
          <li class="nav-item active fancy-link m-3">
            <%= link_to "Home", :root %>
          </li>
          <li class="nav-item fancy-link m-3">
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li class="nav-item active fancy-link m-3">
            <%= link_to "Your Readings", daily_readings_path%>
          </li>
          <li class="nav-item active fancy-link m-3">
            <%= link_to "Home", :root %>
          </li>
          <li class="nav-item fancy-link m-3">
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% end %>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_questions.html.erb
<div class="single-modal">
  <div class="question-buttons">
    <button type="button" class="subscription-btn m-0" data-toggle="modal" data-target="#questionModal">
      <div class="subscription-img">
        <%= cl_image_tag("https://res.cloudinary.com/dm37aktki/image/upload/v1646655636/Depositphotos_10479229_S_dhwxrs.jpg") %>
      </div>
      Questions
    </button>
  </div>
          <!-- Modal -->

  <div class="modal fade" id="questionModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Daily Reading Questions:</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
          <div class="modal-body">
            <% @questions_with_answers.each_with_index do |q_w_a, i| %>
              <%= q_w_a[:question].content if i < 4 %>
              <br><br>
            <% end %>
          </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

        </div>
      </div>
    </div>
  </div>

</div>

app/views/shared/_sidebar.html.erb
<div class="sidebar">
  <div class="sidebar-links">
    <%= link_to "Yesterday", "#" %>
    <%= link_to "Today", reading_group_path %>
    <%= link_to "Tomorrow", "#" %>
  </div>
</div>